FROM mysql:5.6

ENV DEBIAN_FRONTEND noninteractive
ENV MYSQL_ROOT_PASSWORD 'knkA9n7YnzvrDLE'
ENV MYSQL_DATABASE 'notes'
ENV MYSQL_USER 'notes-api'
ENV MYSQL_PASSWORD 'notes-api'

COPY database.sql database.sql

EXPOSE 3306
